const char webCSS[] = "body,textarea,input,select{background:0;border-radius:0;font:16px sans-serif;margin:0}.addon,.btn-sm,.nav,textarea,input,select{outline:0;font-size:1.5em}.smooth{transition:all .2s}.btn,.nav a{text-decoration:none}.container{margin:0 20px;width:auto}@media(min-width:1310px){.container{margin:auto;width:1270px}}.btn,h2{font-size:2em}h1{font-size:3em}.btn{background:#999;border-radius:6px;border:0;color:#fff;cursor:pointer;display:inline-block;margin:2px 0;padding:20px 0px}.btn:hover{background:#888}.btn:active,.btn:focus{background:#777}.btn-a{background:#0ae}.btn-a:hover{background:#09d}.btn-a:active,.btn-a:focus{background:#08b}.btn-b{background:#3c5}.btn-b:hover{background:#2b4}.btn-b:active,.btn-b:focus{background:#2a4}.btn-c{background:#d33}.btn-c:hover{background:#c22}.btn-c:active,.btn-c:focus{background:#b22}.btn-sm{border-radius:4px;padding:10px 14px 11px}label>*{display:inline}form>*{display:block;margin-bottom:10px}textarea,input,select{border:1px solid #ccc;padding:20px 0}textarea:focus,input:focus,select:focus{border-color:#5ab}textarea,input[type=text]{-webkit-appearance:none;outline:0}.addon{box-shadow:0 0 0 1px #ccc;padding:10px 0}.row{margin:1% 0;overflow:auto}.table,.c12{width:100%}.c11{width:91.66%}.c10{width:83.33%}.c9{width:75%}.c8{width:66.66%}.c7{width:58.33%}.c6{width:50%}.c5{width:41.66%}.c4{width:33.33%}.c3{width:25%}.c2{width:16.66%}.c1{width:8.33%}.tc{text-align:center}.tr{text-align:right}input::-webkit-inner-spin-button,input::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}input[type=number]{-moz-appearance:textfield}";
const char webJS[] = "function setSelectedIndex(e,t){for('Asia/Calcutta'==t&&(t='Asia/Kolkata'),i=0;i<e.options.length;i++)if(e.options[i].value==t){e.options[i].selected=!0;break}}";

const char webHEAD[] = "<html><head><link rel='stylesheet' href='a.css' /></head><body><h1 class='tc'>LoRa Gateway Config</h1>";
const char webFOOTER[] = "<script src='a.js'></script></body></html>";

const char webIndex[] = "<div class='container'><a class='btn c12 tc' href='wc'>WiFi Config</a><a class='btn c12 tc' href='ss'>Server Settings</a><a class='btn c12 tc' href='ds'>Device Settings</a><a class='btn c12 tc' href='fw'>Firmware</a><a class='btn c12 tc' href='wec'>Web Console</a><a class='btn-c btn c12 tc' href='fr'>Factory Reset Device</a><a class='btn-a btn c12 tc' href='re'>Restart</a></div>";
const char webWC[] = "<h2 class='tc'>WiFi Config</h2><div class='container'><form method='POST' action='wcs'><input type='text' name='ssid' placeholder='Enter SSID Name' class='c12 tc'><input type='password' name='ssidpw' placeholder='Enter SSID Password' class='c12 tc'><button type='submit' class='btn btn-b c12 tc'>Save</button></form><a class='btn-a btn c12 tc' href='../'>Back to Dashboard</a></div>";
const char webSS[] = "<h2 class='tc'>Server Config</h2><div class='container'><form method='POST' action='sss'><input type='text' name='mqs' placeholder='MQTT Server Address' class='c12 tc' required><input type='number' name='mqp' placeholder='MQTT Port' class='c12 tc' required><input type='text' name='mqt' placeholder='MQTT Topic' class='c12 tc'><input type='text' name='mqu' placeholder='MQTT Username' class='c12 tc'><input type='password' name='mqpw' placeholder='MQTT Password' class='c12 tc'><button type='submit' class='btn btn-b c12 tc'>Save</button></form><a class='btn-a btn c12 tc' href='../'>Back to Dashboard</a></div>";
const char webDS1[] = "<h2 class='tc'>Device Config</h2><div class='container'><form method='POST' action='dcs'><input type='password' name='lpw' placeholder='Set/Change Device Password' class='c12 tc'>";
const char webDS2[] = "UC";
const char webDS3[] = "<select class='c12 tc' name='lbw' required><option value=''>Bandwidth</option><option value='7.8E3'>7.8kHz</option><option value='10.4E3'>10.4kHz</option><option value='15.6E3'>15.6kHz</option><option value='20.8E3'>20.8kHz</option><option value='31.25E3'>31.25kHz</option><option value='41.7E3'>41.7kHz</option><option value='62.5E3'>62.5kHz</option><option value='125E3'>125kHz</option><option value='250E3'>250kHz</option><option value='500E3'>500kHz</option></select><select class='c12 tc' name='lsf' required><option value=''>Spreading Factor</option><option value='7'>SF7</option><option value='8'>SF8</option><option value='9'>SF9</option><option value='10'>SF10</option><option value='11'>SF11</option><option value='12'>SF12</option> </select> <select class='c12 tc' name='lcr' required><option value=''>Coding Rate</option><option value='5'>4/5</option><option value='6'>4/6</option><option value='7'>4/7</option><option value='8'>4/8</option></select><input type='number' name='lfq' placeholder='Enter LoRa Frequency in MHz eg. 866' max='2500' class='c12 tc' required><input type='number' name='lpl' placeholder='Preamble Length' min='6' max='65535' class='c12 tc' required><input type='text' name='lsw' placeholder='Sync Word eg. 39 or 12' class='c12 tc' required><button type='submit' class='btn btn-b c12 tc'>Save</button></form><a class='btn-a btn c12 tc' href='../'>Back to Dashboard</a></div>";

const char webFW[] = "<h2 class='tc'>Firmware Version <span id='fwver'>.....</span></h2><div class='container'><form method='POST' action='fws' enctype='multipart/form-data'><input type='file' name='update' class='c12 tc' required><button type='submit' class='btn btn-b c12 tc'>Save</button></form><a class='btn-a btn c12 tc' href='../'>Back to Dashboard</a></div>";
const char webWEC[] = "<h2 class='tc'>Web Console</h2><div class='container'><textarea id='wect' class='c12' readonly rows='14' wrap='off'></textarea><div class='c12'>&nbsp;</div><form method='POST' action='wecs'><input type='text' name='wecc' placeholder='Enter command to send to Web Console' class='c12'><button type='submit' class='btn btn-b c12 tc'>Send to Console</button></form><a class='btn-a btn c12 tc' href='../'>Back to Dashboard</a></div>";